### ISSUE TITLE
In set configure access token option should not be take space in starting

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/prestashop#3]
When we set access token if we are used space in starting so manage ticket option not working

**How to Reproduce:**

Step 1: Go to **Uvdesk Ticket System -> Set Configuration** here put **Access token with space in starting and ending** and save:

![image](https://user-images.githubusercontent.com/63539748/168067060-ed520784-f6f2-420b-8c6f-cd02a921a530.png)

Step 2: Now click on ticket manage option and here shown an error somthing went wrong:

![image](https://user-images.githubusercontent.com/63539748/168067112-1efb5ed3-4699-4af3-8804-69be7fc455d5.png)

Step 3: Now remove the space from starting and again save it. click on manage ticket option now working with ticket view page.

![image](https://user-images.githubusercontent.com/63539748/168067730-2b28a75e-a2e5-40ab-a4a6-14ed80bbe1ac.png)

**Comment by neerajwebkul** [comment]
Fixed in V4.0.4 [PS 1.7]

**Comment by komal-sh-27** [comment]
I have checked this issue has been resolved now. So I am closing this issue.

![image](https://github.com/uvdesk/prestashop/assets/63539748/8f591657-76fa-4052-b0af-bf15394ed730)
