### ISSUE TITLE
In Prestashop Helpdesk app: When agent assigned from admin side so here showing a pop of error message

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/prestashop#4]
In Prestashop Helpdesk app: When agent assigned from admin side so here showing a pop of error message

**How to Reproduce:**

Step 1: First, helpdesk added with uvdesk

Step 2: Now login with prestashop helpdesk account and assigned agent in the ticket:

![image](https://user-images.githubusercontent.com/63539748/227218910-f9baedbf-aa11-4d14-a9c6-7353ce0dc31a.png)

Step 3: After assigned agent so here showing a pop up like this:

![image](https://user-images.githubusercontent.com/63539748/227219052-207611af-5ec1-49b2-ab18-2cc1f104ace5.png)

**Possible Solution:**

If we agent assigned from prestashop helpdesk so here should be added an agent in the ticket without any error:

**Note: Installed project URL:**

http://uvdesktest.webkul.com/prestashop_1.7/admin472ii4tag/index.php?

**Comment by komal-sh-27** [comment]
I have checked this issue again, now this pop up not showing also agent assigned successfully in tickets with mail received on agent email.

So I am closing this issue.
