### ISSUE TITLE
On customer prestashop helpdesk: When clicks on the collaborator added tickets so here tickets showing a error on customer panel 

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/prestashop#6]
On Prestashop helpdesk: When clicks on the collaborator added tickets so here tickets showing a error on customer panel 

**How to reproduce:**

Step 1: Login with prestashop customer helpdesk account

Step 2: Now collaborator added in the ticket from admin saas dashboard

Step 3: Now clicks on the collaborator added ticket from customer panel so here ticket not opening

![Screenshot from 2023-03-24 13-04-05](https://user-images.githubusercontent.com/63539748/227454770-58d72226-0804-41c0-9219-45ad54117d43.png)

When clicks on the without added any collaborator in ticket so ticket easily opened:

![image](https://user-images.githubusercontent.com/63539748/227455375-19afaaf4-c965-4793-aa19-3a0479ce6c0f.png)

**Note: Collaborator should be added multiple emails from prestashop helpdesk also**
**And if collaborator remove from prestashop helpdesk side so should be removed from uvdesk saas helpdesk**

**Possible Solution:**

If we added collaborator ticket opening so should be open a ticket without any error.

**Comment by komal-sh-27** [comment]
> Note: Collaborator should be added multiple emails from prestashop helpdesk also
And if collaborator remove from prestashop helpdesk side so should be removed from uvdesk saas helpdesk

I have checked again this issue, now collaborators added multiple emails and also removed collaborators from prestashop helpdesk then removed from saas uvdesk 

Also, tickets open with collaborators added in tickets. So I am closing this issue.
