### ISSUE TITLE
On admin panel prestashop account: When clicks on collaborator added ticket or added a collaborator so here showing a n error

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/prestashop#7]
On admin panel prestashop account: When clicks on collaborator added ticket or added a collaborator from uvdesk end so here showing a n error

**How to Reproduce:**

Step 1: Login with prestashop helpdesk account

Step 2: Now when **collaborator added or clicks on collaborator added ticket on prestashop helpdesk** so here showing an error:

![image](https://user-images.githubusercontent.com/63539748/228465692-bee604ac-0477-4c64-8d4a-d66dfcf31632.png)

![Screenshot from 2023-03-29 12-58-22](https://user-images.githubusercontent.com/63539748/228465861-487335e3-86a6-4371-a939-c4624182bb6d.png)

Step 3: Also, **same problem with the tags added in the tickets**, If tags added from uvdesk saas helpdesk then on prestashop HD showing an error

Note: Tags should be added only on tickets added not add in any articles. Then add this article in ticket now check on the prestashop end on admin and customer end, shows an error.

**Possible Solution:**

When collaborator added from prestashop helpdesk side clicks on collaborator added ticket so should be open and collaborator added without any error like customer panel.

**Comment by komal-sh-27** [comment]
I have check again this issue with **v-8.1.2 and Module v-4.0.4**. Now in v-8.1.2, when we add a collaborator from uvdesk end then shows an error like this:

**On customer panel:**

![Screenshot from 2023-10-23 13-02-07](https://github.com/uvdesk/prestashop/assets/63539748/97c04d3d-a06c-4921-a9c3-b27472f7e216)

**On Admin Panel:**

![image](https://github.com/uvdesk/prestashop/assets/63539748/5288b697-c386-467f-9fc9-ea2708c78abb)

**Comment by komal-sh-27** [comment]
This issue is not related to the collaborators added tickets, so I am closing this issue.
