### ISSUE TITLE
On admin prestashop helpdesk: Ticket list should be shown a last reply on ticket instead of ticket creation date

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/prestashop#8]
On admin prestashop helpdesk: Ticket list should be shown a last reply on ticket instead of ticket creation date

**How to Reproduce:**

Step 1: Login with prestashop and saas uvdesk dashboard

Step 2: Now check on the saas uvdesk panel here ticket showing on the last reply on tickets:

**In Open tab ticket:**

![image](https://user-images.githubusercontent.com/63539748/227459485-62840832-3159-44df-834a-780569f93284.png)

**In  Answered tab ticket:**

![image](https://user-images.githubusercontent.com/63539748/227459794-54cb4b69-6c76-4862-b586-4376c553d37f.png)

Step 3: Now check on the prestashop helpdesk here ticket showing on the ticket creation date:

**In Open tab ticket:**

![image](https://user-images.githubusercontent.com/63539748/227459554-3d8289f1-974f-4675-bab4-95b523f562df.png)

**In  Answered tab ticket:**

![image](https://user-images.githubusercontent.com/63539748/227459708-e2360bbf-5c03-4a77-ab24-c3a2c489ba66.png)

**Note: Also, on customer panel should be last reply ticket.**

**Comment by neerajwebkul** [comment]
Fixed in V4.0.4 [PS 1.7]

**Comment by komal-sh-27** [comment]
I have verified this issue again with **v.8.1.2**, now this issue has been resolved with tickets list showing accordingly ticket last replied. So I am closing this issue.

**On Prestashop HD:**

![image](https://github.com/uvdesk/prestashop/assets/63539748/912caee3-27f7-4bef-a170-7596b1d5b31d)

**On Uvdesk HD:**

![image](https://github.com/uvdesk/prestashop/assets/63539748/1aec5c0b-4210-4844-9f29-c1e80aaa7ce0)
