### ISSUE TITLE
On admin prestashop helpdesk: When using ticket filter so here clicks on another tab so filters removed automatically

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/prestashop#9]
On admin prestashop helpdesk: When using ticket filter so here clicks on another tab so filters removed automatically

**How to Reproduce:**

**Issue 1:**

Step 1: On admin panel of prestashop helpdesk app and using ticket filters:

![image](https://user-images.githubusercontent.com/63539748/227461346-81311d4c-7be1-4292-bb91-1b0e5a7bfafb.png)

Step 2: Now agent filter and here showing correctly but when **clicks on Answered tab** or any other tab of **Open tab** so here filters automatically removed instead of result showing in Answered tab 

![image](https://user-images.githubusercontent.com/63539748/227462076-f8f5d0b6-60db-4828-ad8b-23d767c9d614.png)

**Issue 2:**

When filter applying in **answered tab** or **any other tab** so here **after applying filters automatically redirect on open tab**

**Possible Solution:**

1. If we have filters so should be shown a another tab data when we click on another tab  like uvdesk saas helpdesk

2. If we filter applying in another tab so should be filter added in same selected tab like uvdesk saas helpdesk

![image](https://user-images.githubusercontent.com/63539748/227463182-b8d92259-c089-4b1b-a5f0-3e585479a29c.png)

**Comment by neerajwebkul** [comment]
Fixed in V4.0.4 [PS 1.7]

**Comment by komal-sh-27** [comment]
I have checked this issue again now this issue has been resolved.

**With the tickets filters issue and clicks on another tab then filters applied issue:**

![image](https://github.com/uvdesk/prestashop/assets/63539748/8c062486-78da-43fc-a807-547c1f4626b5)

So I am closing this issue.
